DEBUG = True

USERNAME = 'root'
PASSWORD = 'Kn*M^+{W'
SERVER = 'localhost'
DB = 'app_api'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = 'APLICATION_SECRET_KEY'